# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  batch: 'true'
  branches:
    include:
      - master

variables:
  solution: '**/Astornomic Solution.sln'
  projectPath: 'Astornomic Solution/Astronomic Catalogs/Astronomic_Catalogs.csproj' 
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: SelfHostedPool20250103
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '$(projectPath)' 
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - script: dir $(Build.ArtifactStagingDirectory) /s
      displayName: 'List files in staging directory'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    pool:
      name: SelfHostedPool20250103
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure subscription for voldmytc'
              appType: 'webApp'
              appName: 'NewAstroCatalogs'
              package: "$(Pipeline.Workspace)/drop/s.zip"
